### ISSUE TITLE
wrong icon alignment?

### ISSUE THREAD

**Issue by carstenbaumhoegger** [mikepenz/Android-Iconics#121]
Hi Mike!

Great lib, I'm just starting to use all of the great features.
I updated the Google Material Icons from `'com.mikepenz:google-material-typeface:2.2.0.1@aar'`  to `'com.mikepenz:google-material-typeface:2.1.0.1.original@aar'` and now the icon alignment seems not to be correct anymore.
I'm using the IconicsTextView to display Icon and Text next to each other and after updating all icons appear to be a bit "higher" relative to the text.
Here are 2 Screenshots to show the problem:
![icons-alt](https://cloud.githubusercontent.com/assets/4333261/12010775/37153cd4-acb4-11e5-826b-f65e8debde8a.JPG) ![icons-neu](https://cloud.githubusercontent.com/assets/4333261/12010787/e7aef166-acb4-11e5-8d33-bd0e61824474.JPG)

Is there a way to align the icons as shown in the left pic again?

Thanks in advance!
Carsten

**Comment by mikepenz** [comment]
@carstenbaumhoegger the icon font packed by google has a wrong baseline of the icon. I haven't yet found a better packaged variant, which keeps the same icon naming. 

To solve this i have added another icon addon which has the correct baseline. It's based on this icon font: http://zavoloklom.github.io/material-design-iconic-font/ 
The problem here is that the naming is a bit different. To use this icon font just add

```gradle
compile 'com.mikepenz:material-design-iconic-typeface:2.2.0.1@aar'
```

**Comment by carstenbaumhoegger** [comment]
@mikepenz alright, I wasn't aware of that.
The naming isn't a real issue, I only use a few icons, the renaming shouldn't take long.
Thanks for the fast reply! :)

**Comment by mikepenz** [comment]
@carstenbaumhoegger yeah it took me a long time to figure out this issue of their icon font. 
It is only a problem if you use the icons within text, so i didn't mention this in the readme.

Ok great :).

No problem
