### ISSUE TITLE
How to use vector images in the application.

### ISSUE THREAD

**Issue by Debjyotinath** [mikepenz/Android-Iconics#140]
Hi Mike,
As it is mentioned that we can use vector/.svg to change color,size etc, i cant find any way to include my vector drawable with Iconics.
So which method and which class should i use to pass the Vector drawable to get the job done

Please help me with this.

**Comment by mikepenz** [comment]
As this library works with Icon fonts you simply create a custom font which contains your vector icons and use this one. In many cases this is already done by the design team because icon fonts are used in the web also. 

if you do not have the icon font, you may consider using the Android Studio built in SVG support which will create drawables for older android versions

https://github.com/mikepenz/Android-Iconics#create-custom-fonts
