### ISSUE TITLE
IconicsImageView from XML layout not loading in app

### ISSUE THREAD

**Issue by MarkOSullivan94** [mikepenz/Android-Iconics#160]
Hi Mike,

I've been trying to use your icons within my XML layouts. The icons work fine whenever I use them programmatically however they're not appearing in XML layouts. I've tried looking at the follow issues to see if there was a solution and none of them helped me in my case: https://github.com/mikepenz/Android-Iconics/issues/67 and https://github.com/mikepenz/Android-Iconics/issues/74

```
<com.mikepenz.iconics.view.IconicsImageView
                android:layout_width="40dp"
                android:layout_height="40dp"
                app:iiv_icon="gmd-home"/>
```

This is my gradle file

```
 compile('com.mikepenz:materialdrawer:5.1.9@aar') {
        transitive = true
    }
 compile 'com.mikepenz:google-material-typeface:2.2.0.1.original@aar' // Google Material Icons
````

I also tried adding what was suggested in this post to my proguard-rules.pro file but it didn't work
https://github.com/mikepenz/Android-Iconics/issues/67#issuecomment-131595331

**Comment by mikepenz** [comment]
@MarkOSullivan94 any log output?

**Comment by MarkOSullivan94** [comment]
@mikepenz  no log output

**Comment by mikepenz** [comment]
@MarkOSullivan94 it is also not working in debug so I assume proguard is not the issue here. 
Have you tried to also set a color? Or a size?

Could it be that you have defined a different `applicationId` in your manifest? This causes the font auto detection to fail, and then you have to register your font as shown here:
https://github.com/mikepenz/Android-Iconics/issues/67#issuecomment-134345018

Also done in the `CustomApplication` here:
https://github.com/mikepenz/Android-Iconics/blob/develop/app/src/main/java/com/mikepenz/iconics/sample/CustomApplication.java#L17

**Comment by MarkOSullivan94** [comment]
@mikepenz I've tried inserting the code ( https://github.com/mikepenz/Android-Iconics/issues/67#issuecomment-134345018 )into my MainActivity which is where I was assuming it has to go, however I'm trying to display it within a card view within a recyclerView. 

This didn't solve this issue so I took it out.

**Comment by mikepenz** [comment]
@MarkOSullivan94 no it should be in the `Application` as shown in the sample app. Or at least before inflating the first `IconicsImageView` in the `Activity` which will contain this view it is already too late

**Comment by MarkOSullivan94** [comment]
@mikepenz I can't see where the CustomApplication class has been used in your sample application. I tried creating it anyway to see what would happen and I added it into the AndroidManifest.xml file and still nothing has changed.

I tried using that code within my Main Activity before doing anything else within the onCreate() method, so it would be before inflating the first `IconicsImageView` which is in a fragment which is only created whenever an option from the navigation drawer is selected.

**Comment by mikepenz** [comment]
@MarkOSullivan94 ok if none of the above helped. Can you provide a small sample showcasing the issue so I can have a deeper look?

**Comment by MarkOSullivan94** [comment]
@mikepenz made a template project for your library which shows the issue. The template will be useful for me setting up your navigation drawer for future apps: https://github.com/MarkOSullivan94/MaterialDrawer-Iconics-Template/

I tried to get the icons to display within main_cardview.xml and this is where they're not being displayed

**Comment by mikepenz** [comment]
@MarkOSullivan94 ok the issue is really easy to fix. :D And not related to the library. 

You use the wrong url for the `app` namespace, because you already had the `card_view` namespace defined. 

By default Android studio will define the `res-auto` url, if this was already defined it will use the `tools` url. If the `tools` url is used android studio is happy but will remove the defined xml properties during the build. 

To fix your issue just remove the `card_view` namespace. Change the `app` namespace to:
```xml
xmlns:app="http://schemas.android.com/apk/res-auto"
```
and change the `card_view:card*` definitions  to `app:card*`

**Comment by MarkOSullivan94** [comment]
Just tried it there now and it works! Had a feeling it was something minor because there was no error coming up in the console. Thanks!
