### ISSUE TITLE
Borderless buttons not capitalized

### ISSUE THREAD

**Issue by artkoenig** [mikepenz/Android-Iconics#177]
After setting up the library with
`LayoutInflaterCompat.setFactory(getLayoutInflater(), new IconicsLayoutInflater(getDelegate()));`

or

```
@Override
protected void attachBaseContext(Context newBase) {
    super.attachBaseContext(IconicsContextWrapper.wrap(newBase));
}
```

the buttons with the style `@style/Widget.AppCompat.Button.Borderless` are not capitalized anymore

**Comment by mikepenz** [comment]
@artkoenig the issue is that `Buttons` do not allow any `Spannables` to be applied on them as soon as they have the `Capitalized` flag. For this reason this is removed and the text is displayed normally. (But Icons are working) The only way around this is to either don't wrap the `Context` and do not use icons on those buttons, or you keep it and set the text of those buttons in capital letters.

**Comment by artkoenig** [comment]
Ok, thanks!
