### ISSUE TITLE
it crop right side of fa-comment icon!!

### ISSUE THREAD

**Issue by hooman-pro** [mikepenz/Android-Iconics#310]
Hi thank you for your good lib.
but it seems have a bug! 
see this screen shot:
![photo_2017-08-02_13-35-58](https://user-images.githubusercontent.com/11981070/28866281-b40222c6-7787-11e7-9cb2-328ffd3d36f9.jpg)

right side of comment is not correct.

my cod is:
<com.mikepenz.iconics.view.IconicsTextView
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:textColor="#555555"
                android:textSize="150dp"
                android:text="{faw-comment}"/>

**Comment by hooman-pro** [comment]
I found that for resoving this problem when put and spec or type some thing after {faw-comment} it will be correct!

<com.mikepenz.iconics.view.IconicsTextView
android:layout_width="wrap_content"
android:layout_height="wrap_content"
android:textColor="#555555"
android:textSize="150dp"
android:text="write something here or put an space!! {faw-comment} write something here or put an space!!"/>

**Comment by mikepenz** [comment]
@hooman-pro if you just want to display an icon. Then use the `IconicsDrawable` directly or the `IconicsImageView

the icon within the `IconicsTextView`may be cut depending on how the text rendering on that device happens

**Comment by hooman-pro** [comment]
ok , but if have text only before {faw-comment} what happent ? like : "string {faw-comment}"

**Comment by mikepenz** [comment]
@hooman-pro I always recommend to use the `IconicsDrawable` directly as it gives much more flexibility rather than the `IconicsTextView`. 

If you really really need it, it follows the rules of text rendering. you might want to add a space afterwards, or make sure enough space is available inside the `TextView`.
Or you have an `TextView` for the text and a `CompoundDrawable` or a `ImageView` or an `IconicsImageView`..

 the color issue is known, and will be fixed soon. Please refer to the other open issue.

**Comment by mikepenz** [comment]
Setting the color for the `IconicsImageView` in xml is fixed. read more here:
https://github.com/mikepenz/Android-Iconics/issues/309
