### ISSUE TITLE
colorRes not working properly on Oreo with alternative resources

### ISSUE THREAD

**Issue by rubengees** [mikepenz/Android-Iconics#362]
Library version: `3.0.0`
Android Version: `8.0.0 (Oreo)`
Device: All i tried on.

I have a color named `icon` defined in both a `values/colors` and `values-night/colors` file.
If the night mode is enabled, I want the color to be loaded from `values-night/colors`.

Consider this minimal example:

```kt
IconicsDrawable(context, icon)
            .sizeDp(something)
            .paddingDp(something)
            .colorRes(R.color.icon)
```

On `Oreo` this leads to an icon always colored with that one defined in `values/colors`.

If I load the color manually like this, it works:

```kt
IconicsDrawable(context, icon)
            .sizeDp(something)
            .paddingDp(something)
            .color(ContextCompat.getColor(context, R.color.icon))
```

I suppose that is caused by:

https://github.com/mikepenz/Android-Iconics/blob/8297bc99b78e2b6ce60a0fae6a25ad488a0c5163/library-core/src/main/java/com/mikepenz/iconics/IconicsDrawable.java#L138

The application `Context` does not know of the current `Theme` thus loading the incorrect color. But that is just a guess of mine.

Thanks for your help in advance!

**Comment by mikepenz** [comment]
@rubengees this works intentionally to prevent issues due to the context no longer being active. 

In case you need to have it activity bound please provide the color as colorInt already:
https://github.com/mikepenz/Android-Iconics/blob/8297bc99b78e2b6ce60a0fae6a25ad488a0c5163/library-core/src/main/java/com/mikepenz/iconics/IconicsDrawable.java#L411
