### ISSUE TITLE
How to use this library version 4.0.2 for FloatingActionButton?

### ISSUE THREAD

**Issue by zivids** [mikepenz/Android-Iconics#485]
I was used the version 3.2.5 for FloatingActionButton by auto layout inflation, but in version 4 the auto layout infaltion is deprecated, should I use the IconicsDrawable for FloatingActionButton?

**Comment by mikepenz** [comment]
@zivids setting the icon programmatically is the best choice yes. 

Alternatively you could extend the `FloatingActionButton` and add iconics support to it if you need it more often. 

There may be an option to do it again via xml in the future, but that depends on how this issue is going to be resolveD: https://github.com/mikepenz/Android-Iconics/issues/481
