### ISSUE TITLE
Update Community Material to latest version

### ISSUE THREAD

**Issue by leroyboerefijn** [mikepenz/Android-Iconics#606]
## About this issue
Community Material (https://materialdesignicons.com/) is at version 6.3.95 by now. Could you please update to the latest release?

## Checklist

- [x] Searched for [similar issues](https://github.com/mikepenz/Android-Iconics/issues)
- [x] Checked out the [sample application](https://github.com/mikepenz/Android-Iconics/tree/develop/app)
- [x] Read the [README](https://github.com/mikepenz/Android-Iconics/blob/develop/README.md)
- [x] Checked out the [CHANGELOG](https://github.com/mikepenz/Android-Iconics/releases)
- [x] Read the [FAQ](https://github.com/mikepenz/Android-Iconics/blob/develop/FAQ.md)
- [x] Checked out the [MIGRATION GUIDE](https://github.com/mikepenz/Android-Iconics/blob/develop/MIGRATION.md)

**Comment by leroyboerefijn** [comment]
Are there any instructions on how I could do this myself?

**Comment by zTrap** [comment]
@leroyboerefijn 
https://github.com/mikepenz/Android-Iconics#create-custom-fonts

**Comment by mikepenz** [comment]
@leroyboerefijn the section about https://github.com/mikepenz/Android-Iconics#create-custom-fonts describes the overall principe. 

Due to the size of and amount of icons in the material design icons sometimes it needs some manual tweaking. 

But generally speaking:
- download the zip with the ttf and css mapping from the icons
- use this: https://android-iconics.mikepenz.com/ and upload the ttf and css to it
- download the files
- there were slight changes in the libraries provided fonts, so the best approach is to copy paste over the enum contents, update the ttf file in the module and update the version number.

**Comment by mikepenz** [comment]
@leroyboerefijn seems @zTrap was faster than me :D.

**Comment by zTrap** [comment]
Just for a few seconds :D

**Comment by leroyboerefijn** [comment]
Awesome! I will give it a try :)

**Comment by leroyboerefijn** [comment]
I get the following error during gradle sync: "This version of the Android Support plugin for IntelliJ IDEA (or Android Studio) cannot open this project, please retry with version 2021.1.1 or newer"

I checked and my Android Studio + plugins are all up to date. Any ideas?
