### ISSUE TITLE
Doesn't work in editor mode

### ISSUE THREAD

**Issue by StNekroman** [mikepenz/Android-Iconics#83]
I've added the next code to my layout:

```xml
<com.mikepenz.iconics.view.IconicsButton
            android:text="{faw-adjust} Button"
            android:layout_width="120dp"
            android:layout_height="60dp"/>

        <com.mikepenz.iconics.view.IconicsImageView
            android:layout_width="72dp"
            android:layout_height="72dp"
            app:iiv_color="@color/dataRow_borderColor"
            app:iiv_icon="faw-home"
            />

        <com.mikepenz.iconics.view.IconicsTextView
            android:text="{faw-home}abc{hif-test}defgh{faw-adjust}ijk{fon-test1}lmnopqrstuv{fon-test2}wxyz"
            android:textColor="@android:color/black"
            android:layout_width="wrap_content"
            android:layout_height="56dp"
            android:textSize="16sp"/>
```

But nothing work as expected. Becuase in each corresponding class I see:

```java
public IconicsImageView(Context context, AttributeSet attrs, int defStyle) {
           super(context, attrs, defStyle);
             **if (!isInEditMode()) {**
                ...
             }
}
```

So rendering is disabled in edit mode in Android Studio.
Why?

**Comment by mikepenz** [comment]
because rendering won't work in the preview of Android-Studio. If i remove this line it won't show your layout at all. If you have a solution how it would render the font let me know, but as far as i know this is not possible.

**Comment by powerhcm8** [comment]
I found a "workaround" is just a way to display the drawable but must work in most cases.

1. Download [Material Design icons](https://github.com/google/material-design-icons).
2. Copy the content of all subsfolder `drawable-anydpi-v21` in paste in `debug/res/drawable-v21`.
3. By using tools namespace to show only in editor and any propriety that uses drawable you can show at least the svg icons from community material and material by google. (eg. tools:background="@drawable/ic_camera_black_24dp").

Since i put the resource in debug folder and used the namespace tools, this will not affect the release version of the app.

**Comment by mikepenz** [comment]
@powerhcm8 that works sure. But you will have some additional effort just to see it in that editor.
