### ISSUE TITLE
Use as text in custom views

### ISSUE THREAD

**Issue by toyongbanatero** [mikepenz/Android-Iconics#84]
Hey Mike. Thanks for this library, it's very awesome. However, I'm trying to put texts with those vector icons in my custom `View` but I'm having some problems because I don't know how to do it right.

I've tried doing it like (on my custom `View`'s `onDraw()` method:
```java
canvas.drawText("Some text {cmd-star}", width, height, paint);
```
but as expected, this will not work. I also tried something like:
```java
canvas.drawText(new Iconics.IconicsBuilder().ctx(getContext()).on("Some text {cmd-star}").build(), width, height, paint);
```
but this complains that I am giving a `SpannableString` where it requires a `String`.

I am thinking of casting it to `String` but I doubt it will work, or will it? What can I do?
Thanks for the help.

**Comment by mikepenz** [comment]
@toyongbanatero you can't use this on a canvas. It seems you mix up a few things. 

There are 2 different things the iconics library does / or can do:
* Icons within text (of `TextView`, `Buttons`, etc...) 
In this case the Iconics-library uses a `SpannableString` and replaces the `{cmd-star}` with the unicode character used to identify the specific icon in the iconfont, and sets a `TypefaceSpanable` on it. So it switches the font for the exact position and then this font is drawn as icon as the unicode char matches to this one
* Icons as Drawable
The other function is that the Iconics-library can create `Drawables` under the hood it uses a similar mechanism to draw the icon instead of normal text. (A bit more complex as it was optimized for performance...) In theory it creates a path out of the specific unicode char (specified via the  `{cmd-star}` notation) in the specific typeface and draws it. 


In your case i think you will have to draw the text. and then also draw the `{cmd-star}` icon as bitmap (you can create a bitmap out of the `IconicsDrawable`

**Comment by toyongbanatero** [comment]
Oh yes. I forgot the about the `IconicsDrawable`. I will try that. Sorry, I was a total noob about making custom `View`s and bumped with this problem of mine. Thanks for the fast reply.
